name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  vibration: ^3.1.3
  shared_preferences: ^2.1.0
  mqtt_client: ^10.8.1
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  usb_serial: ^0.5.2
  rxdart: ^0.28.0
  mobile_scanner: ^7.0.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/omgkawaii-blue-10-cm-kawaii-donut-squeeze-squishy-food-toys-40866696265941.png
  uses-material-design: true